# Generated by Django 5.2.7 on 2025-11-09 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_usuario_fcm_token'),
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fcm_token',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cliente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='commercial.cliente'),
        ),
    ]
