# Generated by Django 5.2.7 on 2025-11-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('predicted_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confidence_interval', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sales_predictions',
            },
        ),
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_file', models.BinaryField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('feature_columns', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'trained_models',
            },
        ),
    ]
