# Generated by Django 5.2.7 on 2025-11-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesprediction',
            options={'verbose_name': 'Predicción de Ventas', 'verbose_name_plural': 'Predicciones de Ventas'},
        ),
        migrations.AlterModelOptions(
            name='trainedmodel',
            options={'ordering': ['-training_date'], 'verbose_name': 'Modelo Entrenado', 'verbose_name_plural': 'Modelos Entrenados'},
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='training_samples',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='model_name',
            field=models.CharField(default='sales_predictor', max_length=100),
        ),
        migrations.AlterModelTable(
            name='salesprediction',
            table='sales_prediction',
        ),
        migrations.AlterModelTable(
            name='trainedmodel',
            table='trained_model',
        ),
    ]
