// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjsSSfxcGI5znUmDiBkKWI_FB8a_7Iw-4',
    appId: '1:962839063489:web:75b0ab19149c608068dd40',
    messagingSenderId: '962839063489',
    projectId: 'smartsales365-316b7',
    authDomain: 'smartsales365-316b7.firebaseapp.com',
    storageBucket: 'smartsales365-316b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUNEWVoBhrd_HutXa9If7Nig4yICCErsM',
    appId: '1:962839063489:android:f3aabe786b19bd1a68dd40',
    messagingSenderId: '962839063489',
    projectId: 'smartsales365-316b7',
    storageBucket: 'smartsales365-316b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDaR84JWa-URrK577wQUZS09E-TdgVLb8',
    appId: '1:962839063489:ios:970f4ea03fefc24b68dd40',
    messagingSenderId: '962839063489',
    projectId: 'smartsales365-316b7',
    storageBucket: 'smartsales365-316b7.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDaR84JWa-URrK577wQUZS09E-TdgVLb8',
    appId: '1:962839063489:ios:970f4ea03fefc24b68dd40',
    messagingSenderId: '962839063489',
    projectId: 'smartsales365-316b7',
    storageBucket: 'smartsales365-316b7.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjsSSfxcGI5znUmDiBkKWI_FB8a_7Iw-4',
    appId: '1:962839063489:web:e5efab61d3ddb6b668dd40',
    messagingSenderId: '962839063489',
    projectId: 'smartsales365-316b7',
    authDomain: 'smartsales365-316b7.firebaseapp.com',
    storageBucket: 'smartsales365-316b7.firebasestorage.app',
  );
}
